const anouncementName = document.querySelector("#anouncement_inputs_name")
const anouncementStartDate = document.querySelector("#anouncement_inputs_Sdate")
const anouncementEndtDate = document.querySelector("#anouncement_inputs_Edate")
const anouncementDescription = document.querySelector("#anouncement_inputs_Description")
const anouncementStatus = document.querySelector()
